### ISSUE TITLE
About English translaton

### ISSUE THREAD

**Issue by QSCTech-Sange** [QSCTech/ClassroomSpider#1]
I have to admit that it's good work but not well translated in English.
For instance, it's not "modefy' but "modify".
Also, "your computer has" not "have".
I haven't checked everything yet.
It will seem more pro as long as you have dealt with whose typos.
Good Luck, TTFish!

**Comment by QSCTech-Sange** [comment]
Maybe I can pull request later.

**Comment by fish98** [comment]
俺居然现在才发现Orz

**Comment by fish98** [comment]
已掩盖丢人事实 1/1
